apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyperdx
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - local-path-storage.yaml

# configurations:
#   - kustomizeconfig.yaml
