apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hyperdx
  namespace: hyperdx
spec:
  interval: 10m
  chart:
    spec:
      chart: hdx-oss-v2
      version: '0.7.2'
      sourceRef:
        kind: HelmRepository
        name: hyperdx
        namespace: hyperdx
      interval: 10m
  values:
    # values-external-clickhouse.yaml

    # clickhouse:
    #   enabled: false
    #   persistence:
    #     enabled: false

    # otel:
    #   enabled: false

    hyperdx:
      replicas: 2
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      ingress:
          enabled: true
          host: "localhost"  # Production domain
          path: "/(.*)"
          pathType: "ImplementationSpecific"
        
      defaultConnections: |
        [
          {
            "name": "ClickHouse Cloud",
            "host": "https://fcb9wwgxlj.us-east-1.aws.clickhouse.cloud",
            "port": 8443,
            "username": "default",
            "password": "Jf_WwIHq6P_~."
          },
          {
            "name": "Local ClickHouse",
            "host": "http://{{ include "hdx-oss.fullname" . }}-clickhouse:8123",
            "port": 8123,
            "username": "app",
            "password": "{{ .Values.clickhouse.config.users.appUserPassword }}"
          }
        ]

      defaultSources: |
        [
          {
            "from": {
              "databaseName": "default",
              "tableName": "otel_logs"
            },
            "kind": "log",
            "timestampValueExpression": "TimestampTime",
            "name": "Logs",
            "displayedTimestampValueExpression": "Timestamp",
            "implicitColumnExpression": "Body",
            "serviceNameExpression": "ServiceName",
            "bodyExpression": "Body",
            "eventAttributesExpression": "LogAttributes",
            "resourceAttributesExpression": "ResourceAttributes",
            "defaultTableSelectExpression": "Timestamp,ServiceName,SeverityText,Body",
            "severityTextExpression": "SeverityText",
            "traceIdExpression": "TraceId",
            "spanIdExpression": "SpanId",
            "connection": "Local ClickHouse",
            "traceSourceId": "Traces",
            "sessionSourceId": "Sessions",
            "metricSourceId": "Metrics"
          },
          {
            "from": {
              "databaseName": "default",
              "tableName": "otel_traces"
            },
            "kind": "trace",
            "timestampValueExpression": "Timestamp",
            "name": "Traces",
            "displayedTimestampValueExpression": "Timestamp",
            "implicitColumnExpression": "SpanName",
            "serviceNameExpression": "ServiceName",
            "bodyExpression": "SpanName",
            "eventAttributesExpression": "SpanAttributes",
            "resourceAttributesExpression": "ResourceAttributes",
            "defaultTableSelectExpression": "Timestamp,ServiceName,StatusCode,round(Duration/1e6),SpanName",
            "traceIdExpression": "TraceId",
            "spanIdExpression": "SpanId",
            "durationExpression": "Duration",
            "durationPrecision": 9,
            "parentSpanIdExpression": "ParentSpanId",
            "spanNameExpression": "SpanName",
            "spanKindExpression": "SpanKind",
            "statusCodeExpression": "StatusCode",
            "statusMessageExpression": "StatusMessage",
            "connection": "Local ClickHouse",
            "logSourceId": "Logs",
            "sessionSourceId": "Sessions",
            "metricSourceId": "Metrics"
          },
          {
            "from": {
              "databaseName": "default",
              "tableName": ""
            },
            "kind": "metric",
            "timestampValueExpression": "TimeUnix",
            "name": "Metrics",
            "resourceAttributesExpression": "ResourceAttributes",
            "metricTables": {
              "gauge": "otel_metrics_gauge",
              "histogram": "otel_metrics_histogram",
              "sum": "otel_metrics_sum",
              "_id": "682586a8b1f81924e628e808",
              "id": "682586a8b1f81924e628e808"
            },
            "connection": "Local ClickHouse",
            "logSourceId": "Logs",
            "traceSourceId": "Traces",
            "sessionSourceId": "Sessions"
          },
          {
            "from": {
              "databaseName": "default",
              "tableName": "hyperdx_sessions"
            },
            "kind": "session",
            "timestampValueExpression": "TimestampTime",
            "name": "Sessions",
            "displayedTimestampValueExpression": "Timestamp",
            "implicitColumnExpression": "Body",
            "serviceNameExpression": "ServiceName",
            "bodyExpression": "Body",
            "eventAttributesExpression": "LogAttributes",
            "resourceAttributesExpression": "ResourceAttributes",
            "defaultTableSelectExpression": "Timestamp,ServiceName,SeverityText,Body",
            "severityTextExpression": "SeverityText",
            "traceIdExpression": "TraceId",
            "spanIdExpression": "SpanId",
            "connection": "Local ClickHouse",
            "logSourceId": "Logs",
            "traceSourceId": "Traces",
            "metricSourceId": "Metrics"
          }
        ]
