apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hyperdx
  namespace: hyperdx
spec:
  interval: 10m
  chart:
    spec:
      chart: hyperdx/hdx-oss-v2
      version: '0.7.2'
      sourceRef:
        kind: HelmRepository
        name: hyperdx
        namespace: hyperdx
      interval: 10m
  # values:
  #   replicaCount: 2