---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-crds
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: emissary-crds
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    enableLegacyVersions: false

 
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: emissary-ingress
  dependsOn:
    - name: emissary-crds
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    waitForApiext:
      enabled: false
